### ISSUE TITLE
Testy jednostkowe

### ISSUE THREAD

**Issue by MacDada** [Glenpl/LYTM#1]
Dajesz, ucz się i pisz, nie ma co odkładać ;-)

**Comment by Glenpl** [comment]
https://github.com/Glenpl/LYTM/commit/e1be2b814710abdf66de4c528d4f23671cefd8d9#commitcomment-16098523

W jaki sposób uczynić bibliotekę robiącą to zapytanie zależnością?
Ewentualnie, w pythonie nie ma żadnego problemu żeby w teście przypisać do nazwy "_get_page_source" metodę zwracającą zawsze stringa z htmlem do testowania.
Np

```
class A():
    def b(self):
        print('abc')

c = A()
c.b()

c.b = lambda: print('def')
c.b()
```

ten kod wypisze
```
abc
def
```

Niemniej zgaduję, że to nie jest rozwiązanie, które uznasz za słuszne :smile:

**Comment by MacDada** [comment]
Mówisz o https://en.wikipedia.org/wiki/Monkey_patch

Ja proponuję https://en.wikipedia.org/wiki/Dependency_injection ;)

**Comment by MacDada** [comment]
W teście sprawdzasz tylko publiczne API metody (czyli metodę `search()`) – to jak ona wewnętrznie rozkłada sobie kod nie powinno Cię interesować – po to piszesz test, żeby te wewnętrzne bebechy móc dowolnie sobie układać – stąd odpada monkey patching.

Chyba, że mamy do czynienia z legacy code, klasą która mia 1000 linii kodu i nie sposób tego inaczej ogarnąć – wtedy można kombinować z „dirty hackami” – ale testy mają za zadanie m.in. pomóc osiągnąć dobry design, więc jak już piszemy nowy kod, to unikamy takich akcji :)

**Comment by Glenpl** [comment]
>W teście sprawdzasz tylko publiczne API metody (czyli metodę search()) 

Czyli nie mam oprócz tego mieć testów do konkretnych metod prywatnych?

**Comment by MacDada** [comment]
> Czyli nie mam oprócz tego mieć testów do konkretnych metod prywatnych?

Tak

**Comment by MacDada** [comment]
> W jaki sposób uczynić bibliotekę robiącą to zapytanie zależnością?

1. Zapomnij przez chwilę o dostępnych bibliotekach. Pomyśl abstrakcyjnie co chcesz zrobić.
2. Potrzebujesz pobrać htmlową treść strony.
3. Nie chcesz się na razie zastanawiać jak się to robi, jaką bibliotekę użyć.
4. Ale chcesz móc dalej pisać kod `YtApi` tak jakbyś już miał ten problem rozwiązany.
5. Piszesz więc, że „chciałbyś mieć jakiś obiekt, który pobierze mi treść strony” i że „mój obiekt api go wymaga”:

    ```
    class YoutTubeApi():
        def __init__(self, page_fetcher):
            self._page_fetcher = page_fetcher
        def search(self, search_string):
            url = /**/
            page_html = self._page_fetcher.fetch(url);
            return /**/
    ```

6. Żeby przetestować `YoutTubeApi` możesz stworzyć prostą implementację fetchera:

    ```
    class TestPageFetcher():
        def fetch(url):
            return "<html>zahardkodowany html tylko do testu dla URLa " + url
    ```
7. Albo mógłbyś bardziej rozbudować sobie testowego fetchera, żeby trzymał sobie np słownik `{ "url1": "html1", "url2": "html2" }`. Albo użyć mocków. Generalnie opcji sporo, żeby sobie ułatawić testowanie.

8. Wreszcie czas na „produkcyjne opcje”: czyli np korzystasz z `urllib`. Robisz więc np `class UrllibPageFetcher`.

9. Żeby ułatwić inicjalizację `YouTubeApi` dla klientów możesz im udostępnić „domyślną” implementację zależności:

    ```
    class YoutTubeApi():
        def __init__(self, page_fetcher = None):
            if page_fetcher is None:
                page_fetcher = new UrllibPageFetcher()
            self.page_fetcher = page_fetcher
    ```

Zalety:

* nie używamy monkey patching
* [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle): `YoutubeApi` przestaje się zajmować rzeźbami po http, delegując to komuś innemu
* korzystający z `YoutubeApi` może podmienić implementację zabaw po http na swoją (np użyć innej, może lepszej, biblioteki)
* w testach także możesz sobie łatwo podmienić zachowanie pobierania na jakieś wygodniejsze niż robienie „prawdziwych” żądań do serwera YT
* produkcyjnie nadal łatwo się korzysta z klasy, bo dajesz domyślną implementację

**Comment by Glenpl** [comment]
Tak, już mam to właściwie gotowe, jeszcze dopieszczam szczegóły, za chwilę pójdzie commit :)

**Comment by Glenpl** [comment]
https://github.com/Glenpl/LYTM/commit/8867e87a8cff2d1637b75a937916d004f2f6faff

**Comment by Glenpl** [comment]
https://github.com/Glenpl/LYTM/commit/cc7734d6d45dad49d61a6488df9dee28f369175c

https://github.com/Glenpl/LYTM/commit/31216281fc8a5d33d675c2d283a4ff0eb615b593

**Comment by Glenpl** [comment]
Kod jest pokryty testami, następne commity dodające nowości do kodu będą zawierały też odpowiadające im testy.

**Comment by Glenpl** [comment]
Kod jest pokryty testami, następne commity dodające nowości do kodu będą zawierały też odpowiadające im testy.
