### ISSUE TITLE
Pokrycie kodu testami

### ISSUE THREAD

**Issue by MacDada** [Glenpl/LYTM#12]
https://coveralls.io/

**Comment by Glenpl** [comment]
https://github.com/Glenpl/LYTM/commit/a2f1cbdb36788ca6c55c9cceb0c753438ee03564

Dodane ale coś się, coś się popsuło i sprawdza też pokrycie biblioteki beautifulsoup co znacznie zaniża wynik, jutro postaram się to naprawić

**Comment by MacDada** [comment]
to teraz doprowadź żeby wszędze było zielono ;-)

**Comment by Glenpl** [comment]
https://github.com/Glenpl/LYTM/commit/b043aa15f3bbd858532c4d60329d0ce05980394d

Poprawione

----

Jutro zajmę się podniesieniem poziomu pokrycia kodu testami, na ten moment jest 69% czy czym music_player.py ma 0%

**Comment by Glenpl** [comment]
O music_player.py - nie będę już tutaj pisał, wszystko jest w opisie tego commita.

https://github.com/Glenpl/LYTM/commit/60c7d64ea06ec9ca22a52de2e3087e080670ae0a

----

https://coveralls.io/github/Glenpl/LYTM?branch=master


coveralls wskazuje obecnie 92.27% pokrycia kodu testami.

**Comment by Glenpl** [comment]
https://coveralls.io/builds/5241359

Pokrycie kodu testami wynosi 100%. Zamykam.
