### ISSUE TITLE
Jakaś automatyczna zabawka do sprawdzania jakości kodu

### ISSUE THREAD

**Issue by MacDada** [Glenpl/LYTM#2]
https://landscape.io/ lub coś w tym stylu?

Idea jest taka, że puszczasz commita, a toś Ci komentuje „standardowe problemy” z kodem czy tam pokazuje jakąś flagę, która mówi o jakości kodu.

**Comment by Glenpl** [comment]
00ae65a3a15318c64415a2f01677d8e22594c001
f8f4c745ba6c794a39896b6435432fc59967be91

Coś podobnego będzie jeszcze potrzebne do odpalania testów, tak?

**Comment by MacDada** [comment]
nom

**Comment by Glenpl** [comment]
Zamykam, to do testów będę linkował w https://github.com/Glenpl/LYTM/issues/1
