### ISSUE TITLE
Fetcher: keszowanie wyników

### ISSUE THREAD

**Issue by MacDada** [Glenpl/LYTM#4]
jak odpali się `search` z tymi samymi słowami kluczowymi, to bez sensu od nowa odpytywać serwer yt (dosyć powolny proces)

przydałby się jakiś kesz.

proponowane sposoby zachowywania kesza:

* w ramie appki
* memcached
* pliki w `/tmp`
* bazka

**Comment by MacDada** [comment]
Zastanów się jak to zrealizować i daj znać. Podpowiem ewentualnie inny sposób – a może wpadniemy na to samo? ;-)

**Comment by Glenpl** [comment]
Ok, od razu tylko może powiem, że graficznym środowiskiem tej apki ma być przeglądarka, jednak nie ma być to aplikacja webowa - backend będzie siedział na komputerze klienta, przeglądarka będzie tylko i wyłącznie gui.

**Comment by MacDada** [comment]
A co nas GUI na tym etapie obchodzi? Robimy bibliotekę ;-)

GUI może być w konsoli, a wideo ascii-artem, whatever ;)

**Comment by MacDada** [comment]
Choć generalnie jeśli wyznaczyłeś sobie jakiś deadline, to mów – bo co czym innym jest pisanie dla nauki, a czym innym realne robienie produktu – to drugie częściej wymaga kompromisów jakościowych ze względu czas :)

**Comment by Glenpl** [comment]
Deadline żadnego nie ma, apkę piszę dla użytku własnego i dla nauki, niedługo napiszę opis w readme o co w ogóle chodzi, dlaczego wymyślam koło od nowa (pisanie własnego yt api zamiast używania tego oficjalnego) itp.

**Comment by Glenpl** [comment]
YoutubeSearch.search() dla danego htmla zwraca zawsze dokładnie te same wyniki, które w realnym użyciu z prawdziwymi wynikami z yt powinny być prawidłowe przez co najmniej kilka najbliższych dni. Można zatem gotowe wyciągnięte VideoSignature(s) dla danego zapytania wrzucić np. do jakiejś bazy danych i ustawić max age po którym uznaje się, że nie są już prawidłowe i przy następnym zapytaniu muszą zostać zastąpione na np. 7 dni.

**Comment by MacDada** [comment]
Yep, zwrotki od YT możesz keszować (w ramie, memcached czy bazce – gdzie to już „szczegół” ;)).

**Comment by Glenpl** [comment]
Niedługo będę musiał zająć się kwestią keszowania, krystalizuje się już jak będzie wyglądać całe api, można zaplanować w jaki sposób zaimplementować keszowanie aby było elastyczne i pozwalało na podpięcie go do różnych zapytań i aspektów api.

**Comment by Glenpl** [comment]
https://github.com/Glenpl/open-yt-api/commit/7ce2dfbc1b2af19827197e0e8fbae52db6ba3264
