### ISSUE TITLE
Testy funkcjonalne

### ISSUE THREAD

**Issue by MacDada** [Glenpl/LYTM#5]
Jakiś test do prawdziwych serwerów yt by się przydał – żeby wykrywał bugi na realnych danych czy też dlatego, że yt w każdej chwili może swoje htmle zmienić

**Comment by MacDada** [comment]
Zanim zaczniesz robić kolejne feature'y – skup się teraz na testach. Bo w sumie mogę wiele tłumaczyć, ale wiele też przyjdzie samo jak rozbijesz się o „jak ja mam to przetestować?” ;-)

Zacznij od funkcjonalnego do YT, bo da Ci warstwę ochronną – będziesz wiedział, że Twój kod rzeczywiście działa.

A potem polecimy z jednostkowymi – i już nowe rzeczy żeby nie leciały bez testów.

**Comment by Glenpl** [comment]
Czyli mam po prostu zrobić test taki sam jak je już istniejące i pobrać w nim prawdziwą stronę yt? Czy test w którym pobieram tylko stronę yt i sprawdzam parserem czy zawiera elementy które ma zawierać?

**Comment by MacDada** [comment]
* pobierz realną stronę bez wyników (np szukaj „qmqmqmqmqmqmqqmqmqmqmq”) – zobacz czy obsługiwane jest tak jak oczekujesz (czyli zwraca pustą listę)
* pobierz realną stronę z jakimś popularnym hasłem (np „pop music”) – zobacz, że załadował co najmniej ileś tam wyników i że udało Ci się pobrać oczekiwane cechy (np nie wiesz jakie będą tytuły filmów, ale wiesz, że na pewno nie będą puste, etc).

takie zabezpieczenie, że – jak coś zwalisz albo yt zmieni – będziesz miał info

**Comment by Glenpl** [comment]
Potrzebne testy funkcjonalne dla metody get_video klasy YoutubeApi.

**Comment by Glenpl** [comment]
Test dodany
