### ISSUE TITLE
Rozszerzenie możliwości YoutubeApi.get_video

### ISSUE THREAD

**Issue by Glenpl** [Glenpl/LYTM#9]
Powinna być możliwość przekazania nie tylko pełnego `VideoSignature` ale też samego id filmu, reszta informacji powinna zostać wtedy uzupełniona przy zapytaniu.

**Comment by MacDada** [comment]
w ogóle wywal przekazywanie VideoSignature na rzecz samego id – po co mnożyć byty?

**Comment by Glenpl** [comment]
Racja, tak będzie prościej

**Comment by Glenpl** [comment]
- [ ] Zmienienie otrzymywanego argumentu z signature na samo id
- [ ] dostosowanie parsera do tej zmiany
